CREATE DATABASE registerDB;
ALTER DATABASE registerDB owner = "safidison"@"localhost";
USE registerDB;

CREATE TABLE reservations (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nom VARCHAR(255) NOT NULL,
  date DATE NOT NULL,
  heure TIME NOT NULL
);

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nom VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  motDePasse VARCHAR(255) NOT NULL
);
